import { Random } from "../engine/random";
import { compile, rewrite } from "./expressions";
import { inputs } from "./tasks";
import {
  BASE,
  type CorpusEntry,
  type Example,
  type Expr,
  type Macro,
  type PriorData,
} from "./types";
const WIDTH = 16,
  FEATURES = 25;
export function features(examples: Example[]): number[] {
  return examples.slice(0, FEATURES).map((e) => Math.tanh(e.output / 4));
}
function softmax(z: number[]): number[] {
  const m = Math.max(...z),
    e = z.map((v) => Math.exp(v - m)),
    s = e.reduce((a, b) => a + b, 0);
  return e.map((v) => v / s);
}
export function distribution(
  p: PriorData | undefined,
  examples: Example[],
  ops: string[],
): number[] {
  if (!p) return ops.map(() => 1 / ops.length);
  const x = [...features(examples), 1];
  const h = [
    ...p.w1.map((row) => Math.tanh(row.reduce((s, w, i) => s + w * x[i], 0))),
    1,
  ];
  const z = softmax(
    p.w2.map((row) => row.reduce((s, w, i) => s + w * h[i], 0)),
  );
  const mapped = ops.map((op) => z[p.ops.indexOf(op)] ?? 0),
    sum = mapped.reduce((a, b) => a + b, 0);
  return mapped.map(
    (v) => 0.85 * (sum ? v / sum : 1 / ops.length) + 0.15 / ops.length,
  );
}
export function operatorCounts(
  e: Expr,
  ops: string[],
  counts = ops.map(() => 0.05),
): number[] {
  const i = ops.indexOf(e.op);
  if (i >= 0) counts[i]++;
  e.args.forEach((a) => operatorCounts(a, ops, counts));
  return counts;
}
export function fitPrior(
  corpus: CorpusEntry[],
  macros: Macro[],
  seed: number,
): PriorData {
  const rng = new Random(seed),
    ops = [...BASE, ...macros.map((m) => m.name)];
  const p: PriorData = {
    ops,
    w1: Array.from({ length: WIDTH }, () =>
      Array.from({ length: FEATURES + 1 }, () => (rng.next() - 0.5) * 0.3),
    ),
    w2: ops.map(() =>
      Array.from({ length: WIDTH + 1 }, () => (rng.next() - 0.5) * 0.3),
    ),
    samples: 0,
    loss: 0,
  };
  const examples = inputs(301, 25, 3);
  const rows = corpus.map((c) => ({
    examples: c.task.examples,
    tree: rewrite(c.tree, macros),
  }));
  // Sleep examples are generated by executing sampled programs. No oracle ASTs.
  const dream = (depth: number): Expr => {
    if (depth <= 0 || rng.next() < 0.35)
      return rng.next() < 0.7
        ? { op: "arg", args: [], value: rng.int(2) }
        : { op: "const", args: [], value: rng.pick([-1, 0, 1, 2]) };
    const op = rng.pick(ops),
      arity =
        op === "neg"
          ? 1
          : BASE.includes(op)
            ? 2
            : macros.find((m) => m.name === op)!.arity;
    return { op, args: Array.from({ length: arity }, () => dream(depth - 1)) };
  };
  for (let i = 0; i < 128; i++) {
    const tree = dream(2 + rng.int(2)),
      f = compile(tree, macros);
    rows.push({
      tree,
      examples: examples.map((input) => ({ input, output: f(...input) })),
    });
  }
  const data = rows.map((row) => {
    const c = operatorCounts(row.tree, ops),
      sum = c.reduce((a, b) => a + b, 0);
    return { x: [...features(row.examples), 1], target: c.map((v) => v / sum) };
  });
  p.samples = data.length;
  for (let epoch = 0; epoch < 55; epoch++) {
    let loss = 0;
    for (let j = 0; j < data.length; j++) {
      const { x, target } = data[rng.int(data.length)];
      const h = [
        ...p.w1.map((row) =>
          Math.tanh(row.reduce((s, w, i) => s + w * x[i], 0)),
        ),
        1,
      ];
      const probs = softmax(
        p.w2.map((row) => row.reduce((s, w, i) => s + w * h[i], 0)),
      );
      const delta = probs.map((v, i) => v - target[i]);
      const hidden = Array.from(
        { length: WIDTH },
        (_, k) =>
          delta.reduce((s, d, i) => s + d * p.w2[i][k], 0) * (1 - h[k] * h[k]),
      );
      for (let i = 0; i < ops.length; i++)
        for (let k = 0; k <= WIDTH; k++) p.w2[i][k] -= 0.025 * delta[i] * h[k];
      for (let k = 0; k < WIDTH; k++)
        for (let i = 0; i <= FEATURES; i++)
          p.w1[k][i] -= 0.025 * hidden[k] * x[i];
      loss -= target.reduce((s, t, i) => s + t * Math.log(probs[i] + 1e-12), 0);
    }
    p.loss = loss / data.length;
  }
  return p;
}
