import { readFileSync, writeFileSync, existsSync, mkdirSync } from "node:fs";
import { gunzipSync, gzipSync } from "node:zlib";
import { languageValueFeatures } from "../src/joint/language-value";
import type { Genome } from "../src/joint/genome";
const source = "output/joint/replication-v1",
  folder = "output/joint/language-value-v1";
if (existsSync(`${folder}/data.json.gz`))
  throw new Error("Preserve value dataset");
const protocol = JSON.parse(readFileSync(`${source}/protocol.json`, "utf8"));
const rows: {
  seed: number;
  round: number;
  stage: string;
  language: string;
  split: string;
  x: number[];
  y: number;
  weight: number;
  genome: Genome;
  context: Parameters<typeof languageValueFeatures>[1];
}[] = [];
for (const seed of protocol.config.seeds) {
  const path = `${source}/seed-${seed}.json.gz`;
  if (!existsSync(`${source}/seed-${seed}.summary.json`))
    throw new Error(
      `All predeclared replications must finish before fitting: missing ${seed}`,
    );
  const run = JSON.parse(gunzipSync(readFileSync(path)).toString());
  if (run.protocolHash !== protocol.protocolHash)
    throw new Error("Mixed protocols");
  for (const round of run.rounds)
    for (const stage of ["screen", "medium"]) {
      const batch: {
        genome: Genome;
        score: number;
        rows: { task: string; result: { budget: number } }[];
      }[] = round[stage];
      const base = batch.find((r) => r.genome.macros.length === 0);
      if (!base) throw new Error("Missing paired base");
      const tasks = new Set(base.rows.map((r) => r.task)).size,
        reps = base.rows.length / tasks;
      const context = {
        corpus: round.corpus,
        training: protocol.config.training,
        budget: base.rows[0].result.budget,
        tasks,
        reps,
      };
      for (const race of batch)
        rows.push({
          seed,
          round: round.round,
          stage,
          language: race.genome.id,
          split: seed <= 11 ? "training" : seed <= 15 ? "validation" : "test",
          x: languageValueFeatures(race.genome, context),
          y: race.score - base.score,
          weight: Math.sqrt(tasks * reps),
          genome: race.genome,
          context,
        });
    }
}
mkdirSync(folder, { recursive: true });
writeFileSync(
  `${folder}/data.json.gz`,
  gzipSync(
    JSON.stringify({
      version: "semantic-library-value-v1",
      sourceProtocolHash: protocol.protocolHash,
      rows,
    }),
  ),
);
writeFileSync(
  `${folder}/data-manifest.json`,
  JSON.stringify(
    {
      sourceProtocolHash: protocol.protocolHash,
      features: rows[0].x.length,
      rows: rows.length,
      splits: Object.fromEntries(
        ["training", "validation", "test"].map((s) => [
          s,
          rows.filter((r) => r.split === s).length,
        ]),
      ),
      note: "Targets use only paired development-race utility differences, never confirmation/final outcomes. Meta-seeds 0–11 train, 12–15 validate; 16–18 and 42 are untouched model-test seeds. This dataset was generated by full races: it demonstrates no saved compute. A separate prospective run is required. Features are name-free pooled executable semantics, structural costs and training-corpus/search-budget metadata.",
    },
    null,
    2,
  ),
);
console.log({ rows: rows.length, features: rows[0].x.length });
